Improved documentation about persistent storage
The README was a little bit confusing to me. I don't see the reason why someone
should change the config and data directories inside the docker container and
thus I don't see the reason why the first example suggests to do that:

    docker run -p 61616:61616 -p 8161:8161 -e ACTIVEMQ_CONF=/etc/activemq/conf -e ACTIVEMQ_DATA=/var/lib/activemq/data rmohr/activemq

The activemq instance searches for these directories (e.g.
`/etc/activemq/conf`) _inside_ the docker container, so even if you want to use
these directories you have to create them before — inside the container (which
you cannot do as long as you don't change the entrypoint or the `Dockerfile`
itself). If you don't create these directories, docker won't start up.
Long story short: The example line does not work and ends with an exception.

Furthermore, if you are such an advanced user who changes this location, you'll
most likely want to bind these directories, so that you don't loose your data.
But if you bind these directories, you could simply bind them to the default
directories `/opt/activemq/conf` and `/opt/activemq/data` — which is the second
example.

But there is also an issue with the second example: If you bind them to two
newly created directories, docker won't start up too, because the directories
are empty and especially the `conf` directory does not contain any
configuration:

    java.io.FileNotFoundException: class path resource [activemq.xml] cannot be opened because it does not exist

So I removed these examples and improved the documentation so that it gives
some hints how to initialize persistent directories.